# Generated by Django 5.2.6 on 2025-09-10 03:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default=django.utils.timezone.now, help_text='4-digit PIN for authentication', max_length=128, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be exactly 4 digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
